# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PARASOL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PARASOL

  ## 통신 
  pod 'Moya'
  ## 키보드 매니저
  pod 'IQKeyboardManagerSwift'
  ## 네이버 지도
  pod 'NMapsMap'
  

end
