# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PARASOL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PARASOL

  ## 통신 
  pod 'Moya'
  ## 키보드 매니저
  pod 'IQKeyboardManagerSwift'
  ## 네이버 지도
  pod 'NMapsMap'
  ## 토스트 메세지
  pod 'Toast-Swift', '~> 5.0.1'
  ## 토스페이먼츠
  pod 'TossPayments'
  ## 푸쉬알람(Firebase)
  pod 'Firebase/Messaging'
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end